# Generated by Django 5.2 on 2025-04-05 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_user_date_of_birth_user_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('minivan', 'Minivan'), ('camper', 'Camper'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('pickup', 'Pickup'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.car')),
            ],
        ),
    ]
