# Generated by Django 5.2.2 on 2025-06-18 16:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_car_image_car_car_type_car_fuel_type_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveBigIntegerField(validators=[api.models.validate_year]),
        ),
    ]
